/*
 * Tanzplaner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tanzschulerenz.tanzplaner.client.api;

import de.tanzschulerenz.tanzplaner.client.ApiException;
import de.tanzschulerenz.tanzplaner.client.model.CoursesResponse;
import de.tanzschulerenz.tanzplaner.client.model.EntriesResponse;
import de.tanzschulerenz.tanzplaner.client.model.EntryResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();


    /**
     *
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void coursesGetTest() throws ApiException {
        Integer id = 50;
        Integer withEntries = 1;
        String category = "jugendliche";
        Integer showEntryDetails = 1;
                CoursesResponse response = api.coursesGet(id, withEntries, category, showEntryDetails);
        // TODO: test validations
    }

    /**
     *
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void entriesGetTest() throws ApiException {
                EntriesResponse response = api.entriesGet();
        // TODO: test validations
    }

    /**
     *
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void entriesViewIdGetTest() throws ApiException {
        Integer id = 2259;
                EntryResponse response = api.entriesViewIdGet(id);
        // TODO: test validations
    }

}
